// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOTVS.PDV.Infra.Data.Context;

namespace TOTVS.PDV.Infra.Data.Migrations
{
    [DbContext(typeof(DbContextPDV))]
    [Migration("20181213232326_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TOTVS.PDV.Services.Models.Dinheiro", b =>
                {
                    b.Property<int>("IdDinheiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdDinheiro")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<int>("Quantidade");

                    b.Property<int>("Tipo");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<float>("Valor");

                    b.HasKey("IdDinheiro");

                    b.ToTable("Dinheiro");

                    b.HasData(
                        new
                        {
                            IdDinheiro = 1,
                            Ativo = true,
                            Descricao = "100 reais",
                            Quantidade = 2147483647,
                            Tipo = 1,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/pt/d/d2/Nova_familia-100.jpg",
                            Valor = 100f
                        },
                        new
                        {
                            IdDinheiro = 2,
                            Ativo = true,
                            Descricao = "50 reais",
                            Quantidade = 2147483647,
                            Tipo = 1,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/pt/7/7c/Nova_familia-50.jpg",
                            Valor = 50f
                        },
                        new
                        {
                            IdDinheiro = 3,
                            Ativo = true,
                            Descricao = "20 reais",
                            Quantidade = 2147483647,
                            Tipo = 1,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/pt/2/28/Nova_familia-20.jpg",
                            Valor = 20f
                        },
                        new
                        {
                            IdDinheiro = 4,
                            Ativo = true,
                            Descricao = "10 reais",
                            Quantidade = 2147483647,
                            Tipo = 1,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/pt/d/de/Nova_familia-10.jpg",
                            Valor = 10f
                        },
                        new
                        {
                            IdDinheiro = 5,
                            Ativo = true,
                            Descricao = "50 centavos",
                            Quantidade = 2147483647,
                            Tipo = 2,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/commons/e/e5/Moeda_de_50_centavos_da_2%C2%AA_gera%C3%A7%C3%A3o.png",
                            Valor = 0.5f
                        },
                        new
                        {
                            IdDinheiro = 6,
                            Ativo = true,
                            Descricao = "10 centavos",
                            Quantidade = 2147483647,
                            Tipo = 2,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/commons/3/31/Moeda_de_10_centavos_da_2%C2%AA_gera%C3%A7%C3%A3o.png",
                            Valor = 0.1f
                        },
                        new
                        {
                            IdDinheiro = 7,
                            Ativo = true,
                            Descricao = "5 centavos",
                            Quantidade = 2147483647,
                            Tipo = 2,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/commons/5/5f/Moeda_de_5_centavos_da_2%C2%AA_gera%C3%A7%C3%A3o.png",
                            Valor = 0.05f
                        },
                        new
                        {
                            IdDinheiro = 8,
                            Ativo = true,
                            Descricao = "1 centavo",
                            Quantidade = 2147483647,
                            Tipo = 2,
                            UrlImagem = "https://upload.wikimedia.org/wikipedia/commons/c/ce/Moeda_de_1_centavo_da_2%C2%AA_gera%C3%A7%C3%A3o.jpg",
                            Valor = 0.01f
                        });
                });

            modelBuilder.Entity("TOTVS.PDV.Services.Models.Transacao", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdTransacao")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Recebido");

                    b.Property<float>("Total");

                    b.Property<float>("ValorRestante");

                    b.HasKey("IdTransacao");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("TOTVS.PDV.Services.Models.Troco", b =>
                {
                    b.Property<int>("IdTroco")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdTroco")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDinheiro");

                    b.Property<int>("IdTransacao");

                    b.Property<int>("Quantidade");

                    b.HasKey("IdTroco");

                    b.HasIndex("IdDinheiro");

                    b.HasIndex("IdTransacao");

                    b.ToTable("Troco");
                });

            modelBuilder.Entity("TOTVS.PDV.Services.Models.Troco", b =>
                {
                    b.HasOne("TOTVS.PDV.Services.Models.Dinheiro", "Dinheiro")
                        .WithMany("TrocoList")
                        .HasForeignKey("IdDinheiro")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TOTVS.PDV.Services.Models.Transacao", "Transacao")
                        .WithMany("TrocoList")
                        .HasForeignKey("IdTransacao")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
